website_logo: "house.png"
avatar_default: "user.png"
email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
email_maximum: 255
email_minimum: 6
pass_minimum: 6
name_maximum: 50
size: 80
paginates_per_page : 5
avatar_size: 50
avatar_mini_size: 30
micropost_maximum: 140
paginate_theme: "twitter-bootstrap-3"
extension_whitelist: ["jpg", "jpeg", "gif", "png"]
img_maximum: 1
format_date: "%d/%m/%Y"
total_room_min: 0
total_room_max: 5
